// <auto-generated />
using VirtualStore.VirtualStore.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Commerce.Infrastructure.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20240315151644_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commerce.Domain.Entitie.Produto", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<int>("Estoque")
                    .HasColumnType("integer");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<double>("Valor")
                    .HasColumnType("double precision");

                b.HasKey("Id");

                b.ToTable("Produto");
            });
#pragma warning restore 612, 618
        }
    }
}